# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tajmr' do
  pod 'AppCenter/Push', '~> 1.14.0'
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tajmr

  

  platform :ios, '9.0'
  target 'TajmrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Tajmr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tajmr-tvOS

  target 'Tajmr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
